[project]
name = "supabase_demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
    "supabase>=2.18.1",
]
